spring.application.name=api-gateway

# CORS
spring.cloud.gateway.globalcors.corsConfigurations.[/api/**].allowedOrigins=http://localhost:4200
spring.cloud.gateway.globalcors.corsConfigurations.[/api/**].allowedMethods=GET,POST,PUT,DELETE
spring.cloud.gateway.globalcors.corsConfigurations.[/api/**].allowedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations.[/api/**].allowCredentials=true

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always